name: CI

on:
    push:
        branches:
            - "**"
    pull_request:
        branches:
            - main

jobs:
    build:
        name: Lint, Knip & Test
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Install dependencies
              run: npm ci

            - name: Run linter
              run: npm run lint

            # - name: Run Knip
            #   run: npm run knip

            - name: Build library
              run: npm run build
