name: CI

on:
  pull_request:
    branches:
      - main

jobs:
  setup:
    name: Linting and building
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Install dependencies
        run: npm install
      
      - name: Lint
        run: npm run lint
      
      - name: Knip
        run: npm run knip
      
      - name: Build
        run: npm run build
